// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReconciliationReport.Data;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ReconciliationContext))]
    [Migration("20230827144310_initialModel")]
    partial class initialModel
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.NIPInboundTransaction", b =>
                {
                    b.Property<long>("RefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RefId"), 1L, 1);

                    b.Property<string>("AccountDescp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Amount");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("Approvevalue")
                        .HasColumnType("tinyint")
                        .HasColumnName("Approvevalue");

                    b.Property<decimal?>("BalanceAtTransTime")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BalanceAtTransTime");

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryAccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryAccountNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BeneficiaryAccountNumber");

                    b.Property<string>("BeneficiaryBankVerificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("ChannelCode")
                        .HasColumnType("tinyint")
                        .HasColumnName("ChannelCode");

                    b.Property<int?>("CountTrasactionFreq")
                        .HasColumnType("int");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateReactivated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Errcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExceedThreshold")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExceedThresholddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FTReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FTadvice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FTadviceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeeRsp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Feecharge")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Feecharge");

                    b.Property<int?>("GivingNg")
                        .HasColumnType("int");

                    b.Property<decimal?>("GivingNgAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("GivingNgAmount");

                    b.Property<DateTime>("InputDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("InputDate");

                    b.Property<int?>("InwardType")
                        .HasColumnType("int");

                    b.Property<int?>("IsSent")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSterlingCustomer")
                        .HasColumnType("bit");

                    b.Property<string>("LedCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MandateRefNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnquiryRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OriginalInputdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginatorAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatorBankVerificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OriginatorKYCLevel")
                        .HasColumnType("int");

                    b.Property<string>("PAPSSResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PenalAmt")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("PenalAmt");

                    b.Property<int?>("PickedStatus")
                        .HasColumnType("int");

                    b.Property<int?>("ReasonFlag")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RepairStatus")
                        .HasColumnType("int");

                    b.Property<string>("Requery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RequeryTimeReceived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequeryTimeSent")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Restriction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReversalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderBankCode")
                        .HasColumnType("char")
                        .HasColumnName("SenderBankCode");

                    b.Property<string>("SenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendersEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendersMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendersMobile2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("varchar")
                        .HasColumnName("SessionId");

                    b.Property<DateTime?>("SettleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SettleDiff")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SettleDiff");

                    b.Property<byte?>("SettleFlag")
                        .HasColumnType("tinyint")
                        .HasColumnName("SettleFlag");

                    b.Property<string>("SettleRemark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaggingStatus")
                        .HasColumnType("int")
                        .HasColumnName("StaggingStatus");

                    b.Property<int?>("Statusflag")
                        .HasColumnType("int");

                    b.Property<string>("SubAccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SwitchDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TSQcount")
                        .HasColumnType("int")
                        .HasColumnName("TSQcount");

                    b.Property<int?>("ThirdpartyID")
                        .HasColumnType("int");

                    b.Property<string>("ThirdpartyNuban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TransactionProcessed")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransactionProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Transnature")
                        .HasColumnType("tinyint")
                        .HasColumnName("Transnature");

                    b.Property<string>("VatRsp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtellerPrinRsp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WalletAcct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WalletAcctStatus")
                        .HasColumnType("int");

                    b.HasKey("RefId");

                    b.ToTable("NIPInboundTransactionTb", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Domain.Entities.NIPOutwardTransaction", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"), 1L, 1);

                    b.Property<string>("AccountStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AppId")
                        .HasColumnType("int");

                    b.Property<int?>("AppsTransactionType")
                        .HasColumnType("int");

                    b.Property<string>("BeneficiaryBVN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryBankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryKYCLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("ChannelCode")
                        .HasColumnType("tinyint");

                    b.Property<string>("CreditAccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("DebitAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DebitRequeryCounter")
                        .HasColumnType("int");

                    b.Property<string>("DebitRequeryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("DebitResponse")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("DebitServiceRequestTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DebitServiceResponseTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FTAdvice")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FTAdviceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeeResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FeeResponseReversed")
                        .HasColumnType("int");

                    b.Property<string>("FraudAnalyticsReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FraudRequeryResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FraudResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FraudScore")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundsTransferResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsImalTransaction")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWalletTransaction")
                        .HasColumnType("bit");

                    b.Property<string>("KafkaStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LedgerCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIBSSRequeryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIBSSResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnquiryResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnquirySessionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatorBVN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatorEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatorKYCLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OutwardTransactionType")
                        .HasColumnType("int");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrincipalResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrincipalResponseReversed")
                        .HasColumnType("int");

                    b.Property<int?>("PriorityLevel")
                        .HasColumnType("int");

                    b.Property<string>("Restriction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReversalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StatusFlag")
                        .HasColumnType("int");

                    b.Property<string>("SubAccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VatResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VatResponseReversed")
                        .HasColumnType("int");

                    b.Property<string>("WalletAccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tbl_NIPOutwardTransactions", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("ReconciliationReport.Entities.InwardReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANNEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreBankingReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESTINATION_ACCOUNT_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESTINATION_ACCOUNT_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESTINATION_INSTITUTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsCredited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("LAST_12_DIGITS_OF_SESSION_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NARRATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORIGINATOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORIGINATOR_INSTITUTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAYMENT_REFERENCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RESPONSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SESSION_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSACTION_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSACTION_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TransactionExist")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("InwardReports");
                });

            modelBuilder.Entity("ReconciliationReport.Entities.NipInwardBatch", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BatchId");

                    b.ToTable("NipInwardBatches");
                });

            modelBuilder.Entity("ReconciliationReport.Entities.NipOutwardBatch", b =>
                {
                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BatchId");

                    b.ToTable("NipOutwardBatches");
                });

            modelBuilder.Entity("ReconciliationReport.Entities.OutwardReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Amount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BatchId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHANNEL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoreBankingReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESTINATION_ACCOUNT_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESTINATION_ACCOUNT_NO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DESTINATION_INSTITUTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDebited")
                        .HasColumnType("bit");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("bit");

                    b.Property<string>("LAST_12_DIGITS_OF_SESSION_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NARRATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORIGINATOR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORIGINATOR_INSTITUTION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAYMENT_REFERENCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RESPONSE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SESSION_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSACTION_TIME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TRANSACTION_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("TransactionExist")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("OutwardReports");
                });
#pragma warning restore 612, 618
        }
    }
}
